<?php

/**
 * @file
 * Main module file for the Landing pages module.
 */

/**
 * Implements hook_menu().
 */
function gj_landing_pages_menu() {
  $items['admin/config/content/landing_pages'] = array(
    'title' => 'Landing pages settings',
    'description' => 'General settings for landing pages.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gj_landing_pages_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'gj_landing_pages.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_preprocess_page().
 */
function gj_landing_pages_preprocess_page(&$vars) {
  $node = menu_get_object();
  if (!empty($node) && $node->nid == variable_get('gl_landing_page_ictp_infuse_nid')) {
    $vars['theme_hook_suggestions'][] = 'page__landing__ictp_infuse';
    drupal_add_css(drupal_get_path('module', 'gj_landing_pages') .'/css/ictp-infuse.css');
    $vars['request_form'] = drupal_get_form('gj_landing_pages_ictp_infuse');
  }
}

/**
 * Implements ictp_infuse subscription form.
 */
function gj_landing_pages_ictp_infuse($form, &$form_state) {

  $form['description'] = array(
    '#type' => 'markup',
    '#markup' => '<p class="description">' . t('Yes, I want to know more about the new iCtP TM Infuse-kit!') . '</p>',
  );
  $form['name'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Name*'),
      'required' => 'required',
    ),
    '#required' => TRUE,
  );
  $form['email'] = array(
    '#type' => 'emailfield',
    '#attributes' => array(
      'placeholder' => t('Email*'),
      'required' => 'required',
    ),
    '#required' => TRUE,
  );
  $form['company'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Company*'),
      'required' => 'required',
    ),
    '#required' => TRUE,
  );
  $form['country'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => t('Country*'),
      'required' => 'required',
    ),
    '#required' => TRUE,
  );
  $form['send'] = array(
    '#type' => 'submit',
    '#value' => t('Send me more information'),
  );
  return $form;
}

function gj_landing_pages_ictp_infuse_submit($form, &$form_state) {
  $form_values = $form_state['values'];
  $to = variable_get('gl_landing_page_email_recipient');
  $from = variable_get('site_mail');

  $language = language_default();
  $params = $form_values;
  $result = drupal_mail('gj_landing_pages', 'ictp_infuse', $to, $language, $params, $from);
  if ($result['result'] == TRUE) {
    drupal_set_message(t('Your message has been sent.'));
  }
  else {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }

}

/**
 * Implements hook_mail().
 */
function gj_landing_pages_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['language']->language,
  );

  switch ($key) {
    case 'ictp_infuse':
      $message['subject'] = t('iCtP Infuse. Request for more information for @name', array(
        '@name' => $params['name'],
      ), $options);
      $message['body'][] = theme('ictp_infuse_email', array(
        'name' => $params['name'],
        'email' => $params['email'],
        'company' => $params['company'],
        'country' => $params['country'],
        'page' => url(current_path(), array('absolute' => TRUE)),
      ));
      $message['body'][] = check_markup($params['message']);
      break;
  }
}

/**
 * Implements hook_theme().
 */
function gj_landing_pages_theme($existing, $type, $theme, $path) {
  return array(
    'ictp_infuse_email'  => array(
      'template' => 'templates/ictp-infuse-email',
    ),
  );

}
