<footer>
 <span class="footer-container">
   <div class="right">
    <span class="newsletter">
    <?php print render($page['subscribe']); ?>
    </span>
    <span class="social">
    <p>Connect with us</p>
    <a class="facebook" href="https://www.facebook.com/glunzjensen" target="_blank">facebook</a>
    <a class="twitter" href="https://twitter.com/GlunzJensen" target="_blank">twitter</a>
    <a class="linkedin" href="https://www.linkedin.com/company/glunz-&-jensen-a-s" target="_blank">linkedin</a>
    </span>
  </div>
  <div class="left">
    <span class="adress">
      <?php print render($page['adress']); ?>
    </span>
    <span class="work-positive"></span>
  </div>

  </span>
</footer>
