<!--<div class="row-fluid" id="bottombar">-->
<div id="relevant-products-link">
  <a href="#block-views-products-on-solutions-block">Relevant products</a>
</div><!--/relevant-products-link-->
  <div id="footer">
    <div class="wrapper940">
      <span class="topfooter">
      <span class="footermenu container"><?php print render($page['footermenu']); ?></span>
      <span class="socials container">
        <a href="https://twitter.com/GlunzJensen" class="twitter link" target="_blank">twitter</a>
        <a href="https://www.facebook.com/glunzjensen" class="facebook link" target="_blank">facebook</a>
        <a href="https://www.linkedin.com/company/glunz-&-jensen-a-s" class="linkedin link" target="_blank">linkedin</a>
      </span>
      </span><!--/end topfooter-->
      <span class="bottomfooter">
      <span class="adress container"><?php print render($page['adress']); ?></span>
      <span class="signup container"><!--<a href="#">Sign up to our newsletter</a>--></span>
      </span><!--/end bottomfooter-->
    </div><!--/wrapper940-->
  <!--</div>/bottombar-->
</div><!--/footer-->
